### ISSUE TITLE
[Insight] Text files should end with a newline character - in phpspec.yml, line 5

### ISSUE THREAD

**Issue by Tjoosten** [Tjoosten/laravel#22]
**[in phpspec.yml, line 5](https://github.com/Tjoosten/laravel/blob/a383629e7cd02b5672b97921161712f49ea3c029/phpspec.yml#L5)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
suites:
    main:
        namespace: App
        psr4_prefix: App
        src_path: app
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/b397c23b-9d78-434b-a2ad-5f8663254701/analyses/1)_
